### ISSUE TITLE
How to use the MPC tracker

### ISSUE THREAD

**Issue by itsthehoneybadger** [kohonda/mpc_tracker_ros#3]
Hi there, I am quite new to this topic. So I was wondering, how to get the map? Or should I create my own map? 

Thank you in advance.

**Comment by kohonda** [comment]
Yes, you should publish a reference path topic as the "map".
This mpc controller node subscribes `/reference_path` topic (type is [nav_msg/Path](https://docs.ros.org/en/noetic/api/nav_msgs/html/msg/Path.html)) and follow the given reference path. 

For example, to publish the reference path topic, you can use another Global Planner node (https://wiki.ros.org/global_planner) or publish a pre-designed and saved path such as a csv format (https://github.com/kohonda/proj-svg_mppi/blob/main/src/reference_waypoint_loader/src/reference_waypoint_loader.cpp).
